# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(610, 535)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("flush.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pathLabel = QtWidgets.QLabel(self.centralwidget)
        self.pathLabel.setObjectName("pathLabel")
        self.gridLayout.addWidget(self.pathLabel, 0, 0, 1, 1)
        self.PathLine = QtWidgets.QLineEdit(self.centralwidget)
        self.PathLine.setObjectName("PathLine")
        self.gridLayout.addWidget(self.PathLine, 1, 0, 1, 1)
        self.PathButton = QtWidgets.QPushButton(self.centralwidget)
        self.PathButton.setObjectName("PathButton")
        self.gridLayout.addWidget(self.PathButton, 1, 1, 1, 1)
        self.URLLabel = QtWidgets.QLabel(self.centralwidget)
        self.URLLabel.setObjectName("URLLabel")
        self.gridLayout.addWidget(self.URLLabel, 2, 0, 1, 1)
        self.URLLine = QtWidgets.QLineEdit(self.centralwidget)
        self.URLLine.setEnabled(False)
        self.URLLine.setObjectName("URLLine")
        self.gridLayout.addWidget(self.URLLine, 3, 0, 1, 1)
        self.ThumbLabel = QtWidgets.QLabel(self.centralwidget)
        self.ThumbLabel.setObjectName("ThumbLabel")
        self.gridLayout.addWidget(self.ThumbLabel, 4, 0, 1, 1)
        self.URLButton = QtWidgets.QPushButton(self.centralwidget)
        self.URLButton.setEnabled(False)
        self.URLButton.setObjectName("URLButton")
        self.gridLayout.addWidget(self.URLButton, 3, 1, 1, 1)
        self.ThumbnailPlaceholder = QtWidgets.QLabel(self.centralwidget)
        self.ThumbnailPlaceholder.setMinimumSize(QtCore.QSize(128, 72))
        self.ThumbnailPlaceholder.setStyleSheet("")
        self.ThumbnailPlaceholder.setText("")
        self.ThumbnailPlaceholder.setPixmap(QtGui.QPixmap("../meme stash/clarkson/Capture.PNG"))
        self.ThumbnailPlaceholder.setScaledContents(True)
        self.ThumbnailPlaceholder.setAlignment(QtCore.Qt.AlignCenter)
        self.ThumbnailPlaceholder.setObjectName("ThumbnailPlaceholder")
        self.gridLayout.addWidget(self.ThumbnailPlaceholder, 5, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DownloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.DownloadButton.setEnabled(False)
        self.DownloadButton.setObjectName("DownloadButton")
        self.horizontalLayout.addWidget(self.DownloadButton)
        self.DownloadMP3Button = QtWidgets.QPushButton(self.centralwidget)
        self.DownloadMP3Button.setEnabled(False)
        self.DownloadMP3Button.setObjectName("DownloadMP3Button")
        self.horizontalLayout.addWidget(self.DownloadMP3Button)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "100% legal youtube download no virus free"))
        self.pathLabel.setText(_translate("MainWindow", "Download Path"))
        self.PathButton.setText(_translate("MainWindow", "Choose Path"))
        self.URLLabel.setText(_translate("MainWindow", "Video URL"))
        self.ThumbLabel.setText(_translate("MainWindow", "Thumbnail preview"))
        self.URLButton.setText(_translate("MainWindow", "Get URL"))
        self.DownloadButton.setText(_translate("MainWindow", "Download (MP4)"))
        self.DownloadMP3Button.setText(_translate("MainWindow", "Download (MP3)"))
